// Auth Actions
export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';

// User/Company Registration
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const USER_REGISTRATION_DEFAULT = "USER_REGISTRATION_DEFAULT";
export const USER_REGISTRATION_PROGRESS = "USER_REGISTRATION_PROGRESS";
export const COMPANY_LOGO_UPLOAD_SUCCESS = "COMPANY_LOGO_UPLOAD_SUCCESS";
export const COMPANY_LOGO_UPLOAD_FAILED = "COMPANY_LOGO_UPLOAD_FAILED";
export const USER_REGISTRATION_COMPLETED = "USER_REGISTRATION_COMPLETED";

// Profile Updates
export const COMPANY_PROFILE_UPDATE_DEFAULT = "COMPANY_PROFILE_UPDATE_DEFAULT";
export const COMPANY_PROFILE_UPDATE_SUCCESS = "COMPANY_PROFILE_UPDATE_SUCCESS";
export const COMPANY_PROFILE_UPDATE_FAILED = "COMPANY_PROFILE_UPDATE_FAILED";

// Menu Actions
export const MENU_OPEN = "MENU_OPEN";
export const MENU_CLOSE = "MENU_CLOSE";
export const MENU_DEFAULT = "MENU_DEFAULT";

// Other
export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const UNSUBSCRIBED = "UNSUBSCRIBED";
